version: '3.8'

services:

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
    ports:
      - "5050:80"
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgressql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: sensor_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "4000:4000"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: unless-stopped
    networks:
      - app-network

  mqtt-server:
    build:
      context: ./mqtt-server
      dockerfile: Dockerfile
    env_file:
      - ./mqtt-server/.env
    container_name: mqtt-server
    environment:
      - MQTT_BROKER=mqtt://mosquitto:4000
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - mosquitto
      - postgres
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build:
      context: ./dashboard/aircraft
      dockerfile: Dockerfile
    env_file:
      - ./dashboard/aircraft/.env
    container_name: frontend
    depends_on:
      - mqtt-server
    restart: unless-stopped
    ports:
      - "2000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mosquitto_data:
  mosquitto_log:
  postgres_data: